import {
    ArrowPathRoundedSquareIcon, ChatBubbleLeftEllipsisIcon,
    DocumentMagnifyingGlassIcon,
    EnvelopeIcon, FolderIcon,
    LinkIcon,
    MagnifyingGlassIcon,
    CalendarDaysIcon,
    ShareIcon,
    AcademicCapIcon
} from "@heroicons/react/24/outline";

export const dashboardSideBarNav = [
    // { name: 'Job Tracker', href: process.env.SITE_URL+'/user/dashboard/comingSoon', icon: CalendarDaysIcon, current: false },
    { name: 'My Resume', href: process.env.SITE_URL+'/user/dashboard/myResume', icon: DocumentMagnifyingGlassIcon, current: false,
    description: "Create, Edit, Download, Share, Print, and Delete your Gen AI powered resume",
        imgUrl: process.env.SITE_URL+"/images/dashboard/icons/resume.svg",
        imgAlt: "My Resume"},
    { name: 'My Cover Letter', href: process.env.SITE_URL+"/user/dashboard/myCoverLetter", icon: EnvelopeIcon, current: false,
        imgUrl: process.env.SITE_URL+"/images/dashboard/icons/coverLetter.svg",
    description: "Create, Edit, Download, Share, Print, and Delete your Gen AI powered cover letter",
        imgAlt: "My Cover Letter"},
    { name: 'JD Extractor', href: process.env.SITE_URL+"/user/dashboard/jdExtractor", icon: ArrowPathRoundedSquareIcon, current: false,
        imgUrl: process.env.SITE_URL+"/images/dashboard/icons/jobDescriptions.svg",
    description: "Extract key information from a job description (Always FREE)",
        imgAlt: "JD Extractor"},
    { name: 'LinkedIn Connection Message', href: process.env.SITE_URL+'/user/dashboard/linkedInMessage', icon: LinkIcon, current: false,
        imgUrl: process.env.SITE_URL+"/images/dashboard/icons/communication.svg",
    description: "Send connection request with a message to LinkedIn recruiters/professionals",
        imgAlt: "LinkedIn Connection Message"},
    { name: 'Interview Questions', href: process.env.SITE_URL+'/user/dashboard/interviewQuestion', icon: ChatBubbleLeftEllipsisIcon, current: false,
        imgUrl: process.env.SITE_URL+"/images/dashboard/icons/SVG/Idea.svg",
    description: "Prepare for your next interview with our curated list of interview questions and answers. All answers are replied using STAR method.",
        imgAlt: "Interview Questions"},
    { name: 'Mock Interview', href: process.env.SITE_URL+'/user/dashboard/mockInterview', icon: AcademicCapIcon, current: false,
        imgUrl: process.env.SITE_URL+"/images/dashboard/icons/interview.svg",
    description: "Meet Hannah, our AI-powered interview coach, simulates real interview scenarios, personalized questions and real-time feedback on your reply.",
        imgAlt: "Mock Interview"},
    { name: 'Job Search', href: process.env.SITE_URL+'/jobs/search', icon: MagnifyingGlassIcon, current: false,
        imgUrl: process.env.SITE_URL+"/images/dashboard/icons/SVG/JobSeeker.svg",
        description: "Search for jobs using natural language, like the way you speak, to find job opportunities. Get job recommendations based on your resume and cover letter.",
        imgAlt: "AI-Powered Job Search"},
    // { name: 'My Uploaded Resume', href: process.env.SITE_URL+'/user/dashboard/myDocument', icon: FolderIcon, current: false,
    //     imgUrl: process.env.SITE_URL+"/images/dashboard/icons/myDocument.webp",
    // description: "Download, Share, Print, and Delete your resume documents",
    //     imgAlt: "My Documents"},
    { name: 'Refer a Friend', href: process.env.SITE_URL+'/user/dashboard/r', icon: ShareIcon, current: false,
        imgUrl: process.env.SITE_URL+"/images/dashboard/icons/referal_icon.jpg",
        description: "Refer a friend to help them discover our free AI-powered career tools.",
        imgAlt: "Refer a Friend"},

]
