import CommonLayout from "../components/Layout/MainLayout";
import Link from "next/link";


const TermsOfService = () =>{
    return (
        <CommonLayout parent="home"
                      title="ResumeGuru - Terms Of Service"
                      meta_title="ResumeGuru - Terms Of Service"
                      meta_desc={process.env.SEO_DEFAULT_DESCRIPTION}

        >
        <div className="bg-white">
            <div className="mx-auto max-w-7xl py-16 px-6 sm:py-24 lg:px-8">
                <h1 className="text-2xl font-bold leading-10 tracking-tight text-gray-900">Terms Of Service</h1>
<div>

    <p> <strong>Last Updated: March 01, 2024</strong></p>
   <p>
       <strong>OVERVIEW</strong>
   </p>
    <p>
        Welcome to Our ResumeGuru Website (&quot;Website&quot;). This Website is operated and provided by ST TECHNOLOGY LLC (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). The following terms and conditions (&quot;Terms of Service&quot;) govern your access to and use of the Website.</p><p>
</p><p>
    Please read these Terms of Service carefully before accessing or using our website. By accessing or using any part of the site, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions of this agreement, then you may not access the website or use any Services. If these Terms of Service are considered an offer, acceptance is expressly limited to these Terms of Service.
</p>
  <h2>
      <strong>SECTION 1 - Acceptance of Terms</strong>
  </h2>
<h3>
    By accessing or using our Website, you agree to be bound by these Terms of Service, our Privacy Policy, and any additional terms that apply to certain products or services. If you do not agree to these Terms, do not use our Website.
</h3>
    <h2> <strong>SECTION 2 - User Account</strong></h2>
<h3>
    2.1 To access certain features of our Website, you may be required to create a user account. You are responsible for the confidentiality of your account information and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to close your account at any time for any or no reason.
</h3>

  <h2>
      <strong>SECTION 3 -  User Content</strong>
  </h2>
    <h3>
        3.1. You may submit, post, or upload content to the Website, including resumes, personal information, and other materials ("User Content"). By submitting User Content, you grant us a worldwide, non-exclusive, royalty-free, sublicensable, and transferable license to use, reproduce, distribute, modify, adapt, publicly display, and create derivative works from your User Content.
    </h3>
    <h3>
        3.2. You agree not to submit User Content that is unlawful, defamatory, obscene, offensive, or violates the rights of others.
    </h3>

    <h2>  <strong>SECTION 4 - Use of AI Technologies and Limitations</strong></h2>
    <h3>
        4.1. ResumeGuru.io employs artificial intelligence (AI) technologies to enhance the functionality and features of the Website, including but not limited to resume analysis, content suggestions, and user experience improvements.
    </h3>
    <h3>
        4.2. While AI technologies are utilized to provide valuable services, it is important to note that AI systems have limitations. The results generated by AI are based on algorithms and data analysis and may not always be error-free or fully accurate.
    </h3>
    <h3>
        4.3. Users should exercise caution and critical judgment when relying on AI-generated content or recommendations. The Company does not guarantee the absolute accuracy or completeness of AI-generated outputs.
    </h3>
    <h2> <strong>SECTION 5 - Email Opt-In at Registration</strong></h2>
    <h3>
        5.1. When you register for a new account, you will be asked to opt-in to receive email communications from us. This may include newsletters, marketing materials, and other information related to our services.
    </h3>

    <h3>
        5.2. You can choose to opt-out of receiving these communications at any time by following the unsubscribe link included in each email.
    </h3>
    <h3>
        5.3. For more details about how we use your email information, please refer to our Privacy Policy.
    </h3>
    <h2><strong>SECTION 6 - Third-Party Services</strong></h2>
    <h3>
        Our Website may contain links to third-party websites or services that we don’t own or control. We are not responsible for the content or any other aspect of these third-party sites, including their collection of information about you.
    </h3>

    <h2>  <strong>SECTION 7 - Limitation of Liability</strong></h2>
    <h3>
        To the maximum extent permitted by law, we shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages, including damages for loss of profits, goodwill, use, data, or other intangible losses, arising out of or relating to the use of our Website.
    </h3>
    <h2> <strong>SECTION 8 - Governing Law</strong></h2>
    <h3>
        These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of United States.    </h3>

    <h2>  <strong>SECTION 9 - Changes to the Terms</strong></h2>
    <h3> You can review the most current version of the Terms of Service at any time at this page.
        We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes.

    </h3>

    <h2>  <strong>SECTION 10 - CONTACT INFORMATION</strong></h2>
    <h3>
        Questions about the Terms of Service should be sent to us at terms@resumeguru.io
    </h3>
    <h2> <strong>SECTION 11 - Subscription Cancellation and Refund Policy</strong></h2>
    <h3>
        11.1 Non-Prorated Refunds: We do not offer prorated refunds for cancellations of any subscription service. If you decide to cancel your subscription, please note that the cancellation will take effect at the beginning of the next billing cycle.
    </h3>
    <h3>
        11.2 Cancellation Process: To cancel your subscription, you must send an email to info@resumeguru.io with the subject line "Cancel." Please include your account details and any specific requests or feedback in your cancellation email. Our team will process your cancellation request and confirm once it has been completed.
    </h3>
    <h3>
        11.3 Cancellation Process: Upon receiving your cancellation request, we will process it promptly. However, please note that you will continue to have access to your subscription services until the end of your current billing cycle. No refunds will be issued for any remaining days in the current billing cycle following your cancellation.
    </h3>
    <h3>

    </h3>

    <br></br>
    <br></br>
    <p>Our contact information is posted below:</p>
        <p> ResumeGuru</p>

    <p>Email: info@resumeguru.io</p>
</div>

            </div>
        </div>
        </CommonLayout>
    )
}
export default TermsOfService
