let fieldOrDomains = [];
export default fieldOrDomains =[
    { id: 1, name: 'Accounting' , shortName: 'Accounting'},
    { id: 2, name: 'Airlines/Aviation' , shortName: 'Airlines'},
    { id: 3, name: 'Alternative Dispute Resolution',shortName: 'AlternativeDispute' },
    { id: 4, name: 'Alternative Medicine' , shortName: 'AlternativeMedicine'},
    { id: 5, name: 'Animation' , shortName: 'Animation'},
    { id: 6, name: 'Apparel & Fashion', shortName: 'ApparelFashion'},
    { id: 7, name: 'Architecture & Planning' , shortName: 'Architecture'},
    { id: 8, name: 'Arts & Crafts' , shortName: 'ArtsCrafts'},
    { id: 9, name: 'Automotive', shortName: 'Automotive' },
    { id: 10, name: 'Aviation & Aerospace' , shortName: 'AviationAerospace'},
    { id: 11, name: 'Banking', shortName: 'Banking' },
    { id: 12, name: 'Biotechnology', shortName: 'Biotechnology' },
    { id: 13, name: 'Broadcast Media', shortName: 'BroadcastMedia' },
    { id: 14, name: 'Building Materials' , shortName: 'BuildingMaterials'},
    { id: 15, name: 'Business Supplies & Equipment', shortName: 'BusinessSuppliesEquipment' },
    { id: 16, name: 'Capital Markets', shortName: 'CapitalMarkets' },
    { id: 17, name: 'Chemicals', shortName: 'Chemicals' },
    { id: 18, name: 'Civic & Social Organization', shortName: 'CivicSocialOrganization' },
    { id: 19, name: 'Civil Engineering', shortName: 'CivilEngineering' },
    { id: 20, name: 'Commercial Real Estate', shortName: 'CommercialRealEstate' },
    { id: 21, name: 'Computer & Network Security', shortName: 'ComputerNetworkSecurity' },
    { id: 22, name: 'Computer Games', shortName: 'ComputerGames' },
    { id: 23, name: 'Computer / Hardware', shortName: 'ComputerHardware' },
    { id: 24, name: 'Computer / Networking', shortName: 'ComputerNetworking' },
    { id: 25, name: 'Computer / Software Engineering', shortName: 'SoftwareEngineering' },
    { id: 26, name: 'Construction', shortName: 'Construction' },
    { id: 27, name: 'Consumer Electronics', shortName: 'ConsumerElectronics' },
    { id: 28, name: 'Consumer Goods', shortName: 'ConsumerGoods' },
    { id: 29, name: 'Consumer Services', shortName: 'ConsumerServices' },
    { id: 30, name: 'Cosmetics', shortName: 'Cosmetics' },
    { id: 31, name: 'Dairy', shortName: 'Dairy' },
    { id: 32, name: 'Defense & Space', shortName: 'DefenseSpace' },
    { id: 33, name: 'Design', shortName: 'Design' },
    { id: 34, name: 'Education Management', shortName: 'EducationManagement' },
    { id: 35, name: 'E-Learning', shortName: 'E-Learning' },
    { id: 36, name: 'Electrical/Electronic Manufacturing', shortName: 'ElectricalElectronicManufacturing' },
    { id: 37, name: 'Entertainment', shortName: 'Entertainment' },
    { id: 38, name: 'Environmental Services', shortName: 'EnvironmentalServices' },
    { id: 39, name: 'Events Services', shortName: 'EventsServices' },
    { id: 40, name: 'Executive Office', shortName: 'ExecutiveOffice' },
    { id: 41, name: 'Facilities Services', shortName: 'FacilitiesServices' },
    { id: 42, name: 'Farming', shortName: 'Farming' },
    { id: 43, name: 'Financial Services', shortName: 'FinancialServices' },
    { id: 44, name: 'Fine Art', shortName: 'FineArt' },
    { id: 45, name: 'Fishery', shortName: 'Fishery' },
    { id: 46, name: 'Food & Beverages', shortName: 'FoodBeverages' },
    { id: 47, name: 'Food Production', shortName: 'FoodProduction' },
    { id: 48, name: 'Fund-Raising', shortName: 'Fund-Raising' },
    { id: 49, name: 'Furniture', shortName: 'Furniture' },
    { id: 50, name: 'Gambling & Casinos', shortName: 'GamblingCasinos' },
    { id: 51, name: 'Glass, Ceramics & Concrete', shortName: 'GlassCeramicsConcrete' },
    { id: 52, name: 'Government Administration', shortName: 'GovernmentAdministration' },
    { id: 53, name: 'Government Relations', shortName: 'GovernmentRelations' },
    { id: 54, name: 'Graphic Design', shortName: 'GraphicDesign' },
    { id: 55, name: 'Health, Wellness & Fitness', shortName: 'HealthWellnessFitness' },
    { id: 56, name: 'Higher Education', shortName: 'HigherEducation' },
    { id: 57, name: 'Hospital & Health Care', shortName: 'HospitalHealthCare' },
    { id: 58, name: 'Hospitality', shortName: 'Hospitality' },
    { id: 59, name: 'Human Resources', shortName: 'HumanResources' },
    { id: 60, name: 'Import & Export', shortName: 'ImportExport' },
    { id: 61, name: 'Individual & Family Services', shortName: 'IndividualFamilyServices' },
    { id: 62, name: 'Industrial Automation', shortName: 'IndustrialAutomation' },
    { id: 63, name: 'Information Services', shortName: 'InformationServices' },
    { id: 64, name: 'Information Technology & Services', shortName: 'InformationTechnologyServices' },
    { id: 65, name: 'Insurance', shortName: 'Insurance' },
    { id: 66, name: 'International Affairs', shortName: 'InternationalAffairs' },
    { id: 67, name: 'International Trade & Development', shortName: 'InternationalTradeDevelopment' },
    { id: 68, name: 'Internet', shortName: 'Internet' },
    { id: 69, name: 'Investment Banking', shortName: 'InvestmentBanking' },
    { id: 70, name: 'Investment Management', shortName: 'InvestmentManagement' },
    { id: 71, name: 'Judiciary', shortName: 'Judiciary' },
    { id: 72, name: 'Law Enforcement', shortName: 'LawEnforcement' },
    { id: 73, name: 'Law Practice', shortName: 'LawPractice' },
    { id: 74, name: 'Legal Services', shortName: 'LegalServices' },
    { id: 75, name: 'Legislative Office', shortName: 'LegislativeOffice' },
    { id: 76, name: 'Leisure, Travel & Tourism', shortName: 'LeisureTravelTourism' },
    { id: 77, name: 'Libraries', shortName: 'Libraries' },
    { id: 78, name: 'Logistics & Supply Chain', shortName: 'LogisticsSupplyChain' },
    { id: 79, name: 'Luxury Goods & Jewelry', shortName: 'LuxuryGoodsJewelry' },
    { id: 80, name: 'Machinery', shortName: 'Machinery' },
    { id: 81, name: 'Management Consulting', shortName: 'ManagementConsulting' },
    { id: 82, name: 'Maritime', shortName: 'Maritime' },
    { id: 83, name: 'Market Research', shortName: 'MarketResearch' },
    { id: 84, name: 'Marketing & Advertising', shortName: 'MarketingAdvertising' },
    { id: 85, name: 'Mechanical or Industrial Engineering', shortName: 'MechanicalIndustrialEngineering' },
    { id: 86, name: 'Media Production', shortName: 'MediaProduction' },
    { id: 87, name: 'Medical Device', shortName: 'MedicalDevice' },
    { id: 88, name: 'Medical Practice', shortName: 'MedicalPractice' },
    { id: 89, name: 'Mental Health Care', shortName: 'MentalHealthCare' },
    { id: 90, name: 'Military', shortName: 'Military' },
    { id: 91, name: 'Mining & Metals', shortName: 'MiningMetals' },
    { id: 92, name: 'Motion Pictures & Film', shortName: 'MotionPicturesFilm' },
    { id: 93, name: 'Museums & Institutions', shortName: 'MuseumsInstitutions' },
    { id: 94, name: 'Music', shortName: 'Music' },
    { id: 95, name: 'Nanotechnology', shortName: 'Nanotechnology' },
    { id: 96, name: 'Newspapers', shortName: 'Newspapers' },
    { id: 97, name: 'Non-Profit Organization Management', shortName: 'Non-ProfitOrganizationManagement' },
    { id: 98, name: 'Oil & Energy', shortName: 'OilEnergy' },
    { id: 99, name: 'Online Media', shortName: 'OnlineMedia' },
    { id: 100, name: 'Outsourcing/Offshoring', shortName: 'OutsourcingOffshoring' },
    { id: 101, name: 'Package/Freight Delivery', shortName: 'PackageFreightDelivery' },
    { id: 102, name: 'Packaging & Containers', shortName: 'PackagingContainers' },

    { id: 103, name: 'Paper & Forest Products', shortName: 'PaperForestProducts' },
    { id: 104, name: 'Performing Arts', shortName: 'PerformingArts' },
    { id: 105, name: 'Pharmaceuticals', shortName: 'Pharmaceuticals' },
    { id: 106, name: 'Philanthropy', shortName: 'Philanthropy' },
    { id: 107, name: 'Photography', shortName: 'Photography' },
    { id: 108, name: 'Plastics', shortName: 'Plastics' },
    { id: 109, name: 'Political Organization', shortName: 'PoliticalOrganization' },
    { id: 110, name: 'Primary/Secondary Education', shortName: 'PrimarySecondaryEducation' },
    { id: 111, name: 'Printing', shortName: 'Printing' },
    { id: 112, name: 'Professional Training & Coaching', shortName: 'ProfessionalTrainingCoaching' },
    { id: 113, name: 'Project Management', shortName: 'ProjectManagement' },
    { id: 114, name: 'Public Policy', shortName: 'PublicPolicy' },
    { id: 115, name: 'Public Relations & Communications', shortName: 'PublicRelationsCommunications' },
    { id: 116, name: 'Public Safety', shortName: 'PublicSafety' },
    { id: 117, name: 'Publishing', shortName: 'Publishing' },
    { id: 118, name: 'Railroad Manufacture', shortName: 'RailroadManufacture' },
    { id: 119, name: 'Ranching', shortName: 'Ranching' },
    { id: 120, name: 'Real Estate', shortName: 'RealEstate' },
    { id: 121, name: 'Recreational Facilities & Services', shortName: 'RecreationalFacilitiesServices' },
    { id: 122, name: 'Religious Institutions', shortName: 'ReligiousInstitutions' },
    { id: 123, name: 'Renewables & Environment', shortName: 'RenewablesEnvironment' },
    { id: 124, name: 'Research', shortName: 'Research' },
    { id: 125, name: 'Restaurants', shortName: 'Restaurants' },
    { id: 126, name: 'Retail', shortName: 'Retail' },
    { id: 127, name: 'Security & Investigations', shortName: 'SecurityInvestigations' },
    { id: 128, name: 'Semiconductors', shortName: 'Semiconductors' },
    { id: 129, name: 'Shipbuilding', shortName: 'Shipbuilding' },
    { id: 130, name: 'Sporting Goods', shortName: 'SportingGoods' },
    { id: 131, name: 'Sports', shortName: 'Sports' },
    { id: 132, name: 'Staffing & Recruiting', shortName: 'StaffingRecruiting' },
    { id: 133, name: 'Supermarkets', shortName: 'Supermarkets' },
    { id: 134, name: 'Telecommunications', shortName: 'Telecommunications' },
    { id: 135, name: 'Textiles', shortName: 'Textiles' },
    { id: 136, name: 'Think Tanks', shortName: 'ThinkTanks' },
    { id: 137, name: 'Tobacco', shortName: 'Tobacco' },
    { id: 138, name: 'Translation & Localization', shortName: 'TranslationLocalization' },
    { id: 139, name: 'Transportation/Trucking/Railroad', shortName: 'TransportationTruckingRailroad' },
    { id: 140, name: 'Utilities', shortName: 'Utilities' },
    { id: 141, name: 'Venture Capital & Private Equity', shortName: 'VentureCapitalPrivateEquity' },
    { id: 142, name: 'Veterinary', shortName: 'Veterinary' },
    { id: 143, name: 'Warehousing', shortName: 'Warehousing' },
    { id: 144, name: 'Wholesale', shortName: 'Wholesale' },
    { id: 145, name: 'Wine & Spirits', shortName: 'WineSpirits' },
    { id: 146, name: 'Wireless', shortName: 'Wireless' },
    { id: 147, name: 'Writing & Editing', shortName: 'WritingEditing' },

];
